### ISSUE TITLE
Generate list of "beta ideas"

### ISSUE THREAD

**Issue by katjam** [wearedarts/games#9]

**Comment by Nikomus** [comment]
Colouring:
- https://github.com/wearedarts/colouring/issues/5 is a must-do for usability, responsiveness, and keeping the app adaptable for future content
- Able to save/share/print final image
- Able to choose more colours
- Try to keep progress between page changes/visits
- Dynamic routes so there's no hard coding

Pairs:
- See all cards at the start and then shuffle
- Example of what you're trying to match
- Some kind of end state/play again/menus

Games:
- Make the games look exciting to play
